### ISSUE TITLE
运行出错：OSError: cannot identify image file <_io.BytesIO object at 0x0600E480>

### ISSUE THREAD

**Issue by SolidBlock-cn** [Allen0910/MindKing#2]
输入回车开始答题之后，出现如下错误：

Traceback (most recent call last):
  File "C:\Users\pengl_000\Downloads\头脑王者辅助\MindKingExt.py", line 147, in <module>
    img=get_screenshot()
  File "C:\Users\pengl_000\Downloads\头脑王者辅助\MindKingExt.py", line 44, in get_screenshot
    img = Image.open(imgbyte)
  File "C:\Users\pengl_000\Downloads\Python\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x0600E480>

**Comment by SolidBlock-cn** [comment]
经调试，get_screenshot函数中的screenshot变量经过str后的内容有很多的\x。
是不是需要像微信跳一跳辅助器那样有如下语句：
if screenshot_way == 2:
	binary_screenshot = screenshot.replace(b'\r\n', b'\n')
else:
	binary_screenshot = screenshot.replace(b'\r\r\n', b'\n')

**Comment by SolidBlock-cn** [comment]
[screenshot.txt](https://github.com/Allen0910/MindKing/files/2020037/screenshot.txt)
